[
    [
        "mainmenu",
        "home",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "home",
        "widgetName",
        "Continua a guardare"
    ],
    [
        "mainmenu",
        "home",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetPath",
        "plugin://plugin.video.saghe/?azione=widget&che=continua"
    ],
    [
        "mainmenu",
        "home",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "home",
        "widgetName.2",
        "La mia lista"
    ],
    [
        "mainmenu",
        "home",
        "widgetType.2",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetPath.2",
        "plugin://plugin.video.saghe/?azione=widget&che=lista"
    ],
    [
        "mainmenu",
        "home",
        "widgetEnable.2",
        "yes"
    ],
    [
        "mainmenu",
        "home",
        "widget.3",
        "Addon"
    ],
    [
        "mainmenu",
        "home",
        "widgetName.3",
        "Consigliati per te"
    ],
    [
        "mainmenu",
        "home",
        "widgetType.3",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetTarget.3",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetPath.3",
        "plugin://plugin.video.saghe/?azione=widget&che=consigli"
    ],
    [
        "mainmenu",
        "home",
        "widgetEnable.3",
        "yes"
    ],
    [
        "mainmenu",
        "home",
        "widget.4",
        "Addon"
    ],
    [
        "mainmenu",
        "home",
        "widgetName.4",
        "Su Netflix ora - Serie TV"
    ],
    [
        "mainmenu",
        "home",
        "widgetType.4",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetTarget.4",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetPath.4",
        "plugin://plugin.video.saghe/?azione=widget&che=netflix:serietv"
    ],
    [
        "mainmenu",
        "home",
        "widgetEnable.4",
        "yes"
    ],
    [
        "mainmenu",
        "home",
        "widget.5",
        "Addon"
    ],
    [
        "mainmenu",
        "home",
        "widgetName.5",
        "Su Netflix ora - Film"
    ],
    [
        "mainmenu",
        "home",
        "widgetType.5",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetTarget.5",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetPath.5",
        "plugin://plugin.video.saghe/?azione=widget&che=netflix:film"
    ],
    [
        "mainmenu",
        "home",
        "widgetEnable.5",
        "yes"
    ],
    [
        "mainmenu",
        "home",
        "widget.6",
        "Addon"
    ],
    [
        "mainmenu",
        "home",
        "widgetName.6",
        "Su Netflix ora - Anime"
    ],
    [
        "mainmenu",
        "home",
        "widgetType.6",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetTarget.6",
        "videos"
    ],
    [
        "mainmenu",
        "home",
        "widgetPath.6",
        "plugin://plugin.video.saghe/?azione=widget&che=netflix:anime"
    ],
    [
        "mainmenu",
        "home",
        "widgetEnable.6",
        "yes"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetName",
        "Le tue saghe"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetPath",
        "plugin://plugin.video.saghe/?azione=widget&che=saghe"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetName.2",
        "I film delle saghe"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetType.2",
        "videos"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetPath.2",
        "plugin://plugin.video.saghe/?azione=widget&che=film"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetEnable.2",
        "yes"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widget.3",
        "Addon"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetName.3",
        "Novita dai tuoi siti"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetType.3",
        "videos"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetTarget.3",
        "videos"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetPath.3",
        "plugin://plugin.video.saghe/?azione=widget&che=novita"
    ],
    [
        "mainmenu",
        "letuesaghe",
        "widgetEnable.3",
        "yes"
    ],
    [
        "mainmenu",
        "serietv",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetName",
        "Le tue serie TV"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetPath",
        "plugin://plugin.video.saghe/?azione=widget&che=serietv"
    ],
    [
        "mainmenu",
        "serietv",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetName.2",
        "Su Netflix ora - Serie TV"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetType.2",
        "videos"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetPath.2",
        "plugin://plugin.video.saghe/?azione=widget&che=netflix:serietv"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetEnable.2",
        "yes"
    ],
    [
        "mainmenu",
        "serietv",
        "widget.3",
        "Addon"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetName.3",
        "Al cinema ora"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetType.3",
        "videos"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetTarget.3",
        "videos"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetPath.3",
        "plugin://plugin.video.saghe/?azione=widget&che=cinema"
    ],
    [
        "mainmenu",
        "serietv",
        "widgetEnable.3",
        "yes"
    ],
    [
        "mainmenu",
        "documentari",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetName",
        "Natura e animali"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetPath",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:1"
    ],
    [
        "mainmenu",
        "documentari",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetName.2",
        "Spazio e scienza"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetType.2",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetPath.2",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:2"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetEnable.2",
        "yes"
    ],
    [
        "mainmenu",
        "documentari",
        "widget.3",
        "Addon"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetName.3",
        "Preistoria e archeologia"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetType.3",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetTarget.3",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetPath.3",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:3"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetEnable.3",
        "yes"
    ],
    [
        "mainmenu",
        "documentari",
        "widget.4",
        "Addon"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetName.4",
        "Storia"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetType.4",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetTarget.4",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetPath.4",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:4"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetEnable.4",
        "yes"
    ],
    [
        "mainmenu",
        "documentari",
        "widget.5",
        "Addon"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetName.5",
        "I programmi di Discovery e Sky"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetType.5",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetTarget.5",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetPath.5",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:5"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetEnable.5",
        "yes"
    ],
    [
        "mainmenu",
        "documentari",
        "widget.6",
        "Addon"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetName.6",
        "Motori, garage e restauri"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetType.6",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetTarget.6",
        "videos"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetPath.6",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:6"
    ],
    [
        "mainmenu",
        "documentari",
        "widgetEnable.6",
        "yes"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetName",
        "Motori e ingegneria"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetPath",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:7"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetName.2",
        "Disastri e misteri"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetType.2",
        "videos"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetPath.2",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:8"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetEnable.2",
        "yes"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widget.3",
        "Addon"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetName.3",
        "Cronaca e crimine"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetType.3",
        "videos"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetTarget.3",
        "videos"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetPath.3",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:9"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetEnable.3",
        "yes"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widget.4",
        "Addon"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetName.4",
        "Societa, arte e viaggi"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetType.4",
        "videos"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetTarget.4",
        "videos"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetPath.4",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:10"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetEnable.4",
        "yes"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widget.5",
        "Addon"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetName.5",
        "Documentari a catalogo"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetType.5",
        "videos"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetTarget.5",
        "videos"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetPath.5",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:0"
    ],
    [
        "mainmenu",
        "altridocumentari",
        "widgetEnable.5",
        "yes"
    ],
    [
        "mainmenu",
        "cucina",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetName",
        "I programmi"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetPath",
        "plugin://plugin.video.saghe/?azione=widget&che=cucina:1"
    ],
    [
        "mainmenu",
        "cucina",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetName.2",
        "Gli chef"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetType.2",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetPath.2",
        "plugin://plugin.video.saghe/?azione=widget&che=cucina:2"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetEnable.2",
        "yes"
    ],
    [
        "mainmenu",
        "cucina",
        "widget.3",
        "Addon"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetName.3",
        "Imparare a cucinare"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetType.3",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetTarget.3",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetPath.3",
        "plugin://plugin.video.saghe/?azione=widget&che=cucina:3"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetEnable.3",
        "yes"
    ],
    [
        "mainmenu",
        "cucina",
        "widget.4",
        "Addon"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetName.4",
        "Cucine del mondo"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetType.4",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetTarget.4",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetPath.4",
        "plugin://plugin.video.saghe/?azione=widget&che=cucina:4"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetEnable.4",
        "yes"
    ],
    [
        "mainmenu",
        "cucina",
        "widget.5",
        "Addon"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetName.5",
        "Particolari"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetType.5",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetTarget.5",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetPath.5",
        "plugin://plugin.video.saghe/?azione=widget&che=cucina:5"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetEnable.5",
        "yes"
    ],
    [
        "mainmenu",
        "cucina",
        "widget.6",
        "Addon"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetName.6",
        "Cucina a catalogo"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetType.6",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetTarget.6",
        "videos"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetPath.6",
        "plugin://plugin.video.saghe/?azione=widget&che=cucina:0"
    ],
    [
        "mainmenu",
        "cucina",
        "widgetEnable.6",
        "yes"
    ],
    [
        "mainmenu",
        "youtube",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "youtube",
        "widgetName",
        "I canali che segui"
    ],
    [
        "mainmenu",
        "youtube",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "youtube",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "youtube",
        "widgetPath",
        "plugin://plugin.video.saghe/?azione=widget&che=youtube:0"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetName",
        "TV in diretta"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetPath",
        "plugin://plugin.video.saghe/?azione=widget&che=tv"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetName.2",
        "Documentari in diretta"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetType.2",
        "videos"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetPath.2",
        "plugin://plugin.video.saghe/?azione=widget&che=documentari:11"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetEnable.2",
        "yes"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widget.3",
        "Addon"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetName.3",
        "Cucina in diretta"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetType.3",
        "videos"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetTarget.3",
        "videos"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetPath.3",
        "plugin://plugin.video.saghe/?azione=widget&che=cucina:6"
    ],
    [
        "mainmenu",
        "tvindiretta",
        "widgetEnable.3",
        "yes"
    ]
]